---
apiVersion: v1
kind: Service
metadata:
  name: nifi-registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: nifi
    app.kubernetes.io/version: "1.15.2"
spec:
  type: ClusterIP
  ports:
    - port: 18080
      targetPort: 18080
      name: http
  selector:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: nifi
